# Generated by Django 2.2.3 on 2019-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=50)),
                ('long_url', models.CharField(max_length=2048)),
                ('hits', models.IntegerField()),
            ],
        ),
    ]
