# Generated by Django 2.2.3 on 2019-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortner',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlshortner',
            name='short_url',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
